#!/bin/bash
# Autogenerated Launch Script for DeepMind Bot

# 1. Initialize Conda
eval "$(conda shell.bash hook)"

# 2. Activate Environment
echo "Activating 'ros2_humble_env'..."
conda activate ros2_humble_env

# 3. CRITICAL: Unset PYTHONPATH to prevent system python conflicts
unset PYTHONPATH

# 4. Source Environments
# Source Conda ROS setup first to get library paths
source "$CONDA_PREFIX/setup.bash"

# Source Workspace setup
if [ -f "ros2_ws/install/setup.bash" ]; then
    source ros2_ws/install/setup.bash
elif [ -f "ros2_ws/install/setup.zsh" ]; then
    source ros2_ws/install/setup.zsh
fi

# 5. Configure Gazebo Paths (Fixes missing plugins/models)
# Add models from gazebo package and conda environment
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$(ros2 pkg prefix deepmind_bot_gazebo)/share/deepmind_bot_gazebo/models:$CONDA_PREFIX/share/gazebo/models

# Add resource paths
export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH:$(ros2 pkg prefix deepmind_bot_gazebo)/share/deepmind_bot_gazebo:$CONDA_PREFIX/share/gazebo

# Add plugin paths including conda lib directory and ROS packages
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:$CONDA_PREFIX/lib:$(ros2 pkg prefix gazebo_ros)/lib

echo "=============================================="
echo "Gazebo Environment Variables:"
echo "GAZEBO_MODEL_PATH: $GAZEBO_MODEL_PATH"
echo "GAZEBO_PLUGIN_PATH: $GAZEBO_PLUGIN_PATH"
echo "=============================================="
echo "Launching Simulation... (Press Ctrl+C to stop)"
echo "Logs available at ~/.ros/log/"
echo "=============================================="

# Launch with simple configuration (no ros2_control - causes crashes on macOS)
echo "NOTE: Using simplified launch without ros2_control (macOS compatibility)"
ros2 launch deepmind_bot_gazebo start_world_simple.launch.py world:=$(ros2 pkg prefix deepmind_bot_gazebo)/share/deepmind_bot_gazebo/worlds/perception1.world
