#!/bin/bash
# Consolidated Setup and Launch Script for DeepMind Bot
# This script performs a clean install of the environment, builds the workspace,
# and generates a dedicated launch script to run the simulation.

ENV_NAME="ros2_humble_env"

set -e # Exit on error

echo "================================================================"
echo "   DeepMind Bot: Automated Setup & Configuration "
echo "================================================================"

# 1. Initialize Conda
echo "[1/6] Initializing Conda..."
eval "$(conda shell.bash hook)"

# 2. Recreate Environment (Clean Slate)
echo "[2/6] Setting up Conda Environment '$ENV_NAME'..."
# Remove if exists to ensure no conflicts
conda deactivate 2>/dev/null || true
if { conda env list | grep $ENV_NAME; } >/dev/null 2>&1; then
    echo "      Removing existing environment to ensure clean install..."
    conda env remove -n $ENV_NAME -y > /dev/null
fi

# Create with specific versions verified to work on macOS (RoboStack)
# Python 3.11 is required for ros2-controllers compatibility
# NumPy < 2.0 is required for cv_bridge compatibility
echo "      Creating environment (this may take a few minutes)..."
conda create -n $ENV_NAME -c conda-forge -c robostack-staging -c robostack-humble -y \
    python=3.11 \
    "numpy<2.0" \
    ros-humble-desktop \
    colcon-common-extensions \
    compilers cmake pkg-config make \
    ros-humble-cartographer-ros \
    ros-humble-navigation2 \
    ros-humble-nav2-map-server \
    ros-humble-nav2-lifecycle-manager \
    ros-humble-xacro \
    ros-humble-joint-state-publisher-gui \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-gazebo-ros2-control \
    ros-humble-controller-manager \
    ros-humble-ros2controlcli

# 3. Activate and Install Python Libs
echo "[3/6] Installing Python Dependencies..."
conda activate $ENV_NAME

# Fix for macOS: Create symlinks for Gazebo plugins (dylib -> so)
echo "      [Fix] Creating symlinks for Gazebo plugins (dylib -> so)..."
for f in $CONDA_PREFIX/lib/libgazebo*.dylib; do
    if [ -f "$f" ] && [ ! -e "${f%.dylib}.so" ]; then
        ln -sf "$f" "${f%.dylib}.so"
    fi
done

pip install ultralytics

# 4. Build Workspace
echo "[4/6] Building ROS 2 Workspace..."
if [ -d "ros2_ws" ]; then
    cd ros2_ws
    
    # Clean old artifacts to prevent ABI mismatch errors
    rm -rf build install log

    # Force build system to use the Conda environment's Python
    unset PYTHONPATH
    PYTHON_EXE=$(which python)
    NUMPY_INCLUDE=$($PYTHON_EXE -c "import numpy; print(numpy.get_include())")
    
    echo "      Using Python: $PYTHON_EXE"
    echo "      Using NumPy:  $NUMPY_INCLUDE"

    colcon build --symlink-install \
        --packages-select advanced_perception custom_msgs deepmind_bot_description deepmind_bot_gazebo deepmind_bot_navigation deepmind_bot_trajectory_sender \
        --cmake-args \
        -DPython3_EXECUTABLE="$PYTHON_EXE" \
        -DPython3_NumPy_INCLUDE_DIRS="$NUMPY_INCLUDE"
    
    cd ..
else
    echo "Error: 'ros2_ws' directory not found!"
    exit 1
fi

# 5. Generate Dedicated Launch Script
echo "[5/6] Generating 'launch_simulation.sh'..."
cat > launch_simulation.sh << 'EOF'
#!/bin/bash
# Autogenerated Launch Script for DeepMind Bot

# 1. Initialize Conda
eval "$(conda shell.bash hook)"

# 2. Activate Environment
echo "Activating 'ros2_humble_env'..."
conda activate ros2_humble_env

# 3. CRITICAL: Unset PYTHONPATH to prevent system python conflicts
unset PYTHONPATH

# 4. Source Workspace setup (skip conda prefix setup.bash as it causes issues)
if [ -f "ros2_ws/install/setup.bash" ]; then
    source ros2_ws/install/setup.bash
elif [ -f "ros2_ws/install/setup.zsh" ]; then
    source ros2_ws/install/setup.zsh
fi

# 5. Configure Gazebo Paths (Fixes missing plugins/models)
# Add models from gazebo package and conda environment
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$(ros2 pkg prefix deepmind_bot_gazebo)/share/deepmind_bot_gazebo/models:$CONDA_PREFIX/share/gazebo/models

# Add resource paths
export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH:$(ros2 pkg prefix deepmind_bot_gazebo)/share/deepmind_bot_gazebo:$CONDA_PREFIX/share/gazebo

# Add plugin paths including conda lib directory and ROS packages
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:$CONDA_PREFIX/lib:$(ros2 pkg prefix gazebo_ros)/lib

echo "=============================================="
echo "Gazebo Environment Variables:"
echo "GAZEBO_MODEL_PATH: $GAZEBO_MODEL_PATH"
echo "GAZEBO_PLUGIN_PATH: $GAZEBO_PLUGIN_PATH"
echo "=============================================="
echo "Launching Simulation... (Press Ctrl+C to stop)"
echo "Logs available at ~/.ros/log/"
echo "=============================================="

# Launch with verbose output to catch any errors
ros2 launch deepmind_bot_gazebo main_perception1.launch.xml
EOF

chmod +x launch_simulation.sh

# 6. Final Instructions
echo "================================================================"
echo "   Setup Complete!"
echo "================================================================"
echo "To launch the simulation, simply run:"
echo ""
echo "    ./launch_simulation.sh"
echo ""
echo "To run your YOLO Pose Estimation node in a NEW terminal:"
echo ""
echo "    conda activate $ENV_NAME"
echo "    unset PYTHONPATH"
echo "    source ros2_ws/install/setup.zsh"
echo "    ros2 run advanced_perception yolo_pose_estimation_node"
echo "================================================================"
